---
# YAML template
_rust_base: &rust_base
  language: rust
  cache: cargo
  script:
    - cargo clean
    - cargo build
    - cargo test

_coverage: &coverage
  before_cache: |
    if [[ "$TRAVIS_RUST_VERSION" == stable && "$TRAVIS_OS_NAME" == linux ]]; then
      cargo install cargo-tarpaulin -f
    fi
  after_success: |
    if [[ "$TRAVIS_RUST_VERSION" == stable && "$TRAVIS_OS_NAME" == linux ]]; then
      cargo tarpaulin --out Xml
      bash <(curl -s https://codecov.io/bash)
    fi

_linux_x11: &linux_x11
  os: linux
  services:
    - xvfb
  addons:
    apt:
      packages:
        - libxcb-shape0-dev     # Because we use clipboard crate
        - libxcb-xfixes0-dev    # Because we use clipboard crate
        - libssl-dev

matrix:
  allow_failures:
    - os: windows

jobs:
  include:
    - stage: "Linux Tests"
      name: "Rust stable"
      <<: *rust_base
      <<: *linux_x11
      <<: *coverage
      rust: stable

    - stage: "Linux Tests"
      name: "Rust beta"
      if: branch =~ /^(master|develop)$/
      <<: *rust_base
      <<: *linux_x11
      rust: beta

    - stage: "Linux Tests"
      name: "Rust nightly"
      if: type = cron
      <<: *rust_base
      <<: *linux_x11
      rust: nightly

    - stage: "MacOS Tests"
      name: "Rust stable"
      <<: *rust_base
      os: osx
      rust: stable

    - stage: "MacOS Tests"
      name: "Rust beta"
      if: branch =~ /^(master|develop)$/
      <<: *rust_base
      os: osx
      rust: beta

    - stage: "MacOS Tests"
      name: "Rust nightly"
      if: type = cron
      <<: *rust_base
      os: osx
      rust: nightly

    - stage: "Windows Tests"
      name: "Rust stable"
      <<: *rust_base
      os: windows
      rust: stable

    - stage: "Windows Tests"
      name: "Rust beta"
      if: branch =~ /^(master|develop)$/
      <<: *rust_base
      os: windows
      rust: beta

    - stage: "Windows Tests"
      name: "Rust nightly"
      if: type = cron
      <<: *rust_base
      os: windows
      rust: nightly

    - stage: "Deployments"
      name: "Crates.io"
      <<: *rust_base
      <<: *linux_x11
      deploy:
        provider: cargo
        token:
          secure: PLfxWrXDBXlw2NAurRC+nDvozXmvqS05ezWxLkIGVtT48PuhsHbw7eTk8eVyMsuLttlAT7avnR+5lxGCq9Q2nXZUjV2xbq0ewZwEyQ5KXrusFJKNYgamRdSfd7EshfG2NSLN/rObmVh1zeSldk2c8f9wKBMqo+mav5ML3lagXMi2Ls0mZUguuNueoIOjg/RRxZwfK5kdFcIeYoxruRhPhbMbXgbahtl2exwth6QD4xMw4pvqwO4VFE1OvfSc626fC04YbZf1jcfEte0HmnOsnBKOqKBZyO67jyZm+4POGMOLOHbPqNmItz5ucn877C3vkcespXR1y6NHoViOXx8+VBaI3ngSFSSa9Ba1SRWjmxYCgxUHf8qsba8jQnn1UA47aHmdojW+/wbnu9X9LvcEcax08hJ2pew+79jVIRZIRqyDXvaDJUho1zbXvcWPaq1bddxf7+OHsCvG2qdVfjsQ6YEPxIfNn1pmmIlVJzkOeVHed1KkdqabVoBT2MKI61uxe9WHEVZwsOc9BGxJSq5gBAtu6k4VjxfW+rxsvug+4WEPQ/e4cd7yIbss7atCbHuQkIRebgjUHsJlhJ38SIDzGzOo4Mc2QF9DM8TrZ80IS0dXTMxqOekXOH1DjDhmzOSvVWcpFwRAVa6Y+yB91BJsIYZTExGy31VfOYy0rApjfnM=
        on:
          branch: master
